### ISSUE TITLE
Correcting the unstructured landuse=residential polygons in KH

### ISSUE THREAD

**Issue by GRABOSM** [GRABOSM/Grab-Data#111]
While mapping in Cambodia we have found some edits around 111 Changesets  (refer: [https://osmcha.org/filters?aoi=ea6188cd-cc73-4c7f-aeff-2a7a0eeff392](https://osmcha.org/filters?aoi=ea6188cd-cc73-4c7f-aeff-2a7a0eeff392)) which were mapped by the new mapper, who have created huge & multiple polygons were not digitized as per the ground reality and tagged them as landuse & building with a single continuous polygon with unrealistic “name” tag.
The mapper tagged name=viilage 27, D-home 53,44,43…, Home 31,32…, Village 25,28, 27… etc… for the polygons and mentioned the same in the changeset comment.

We have tried to reach the mapper to find out the source of the information. Refer: [https://www.openstreetmap.org/changeset/115383543](https://www.openstreetmap.org/changeset/115383543/#map=15/11.7195/103.8644). Unfortunately, we have not heard back from the mapper and hence we are going and fixing these polygons on the OpenStreetMap. 

**OpenStreetMap Changeset Comment:** `Correcting the unstructured landuse polygons in Cambodia https://github.com/GRABOSM/Grab-Data/issues/111`

![](https://lh6.googleusercontent.com/ts7t0Z236eoZAMPg2HtMid2HNO7Tm204DH7H0ZgkKDWf8sGkcqe3c4S2ppJs_ThWyLmqGOoI4lME6LqFxzrjgO0ojAIpEGk0iHnxVj2PZEUsY59w7ePOsRASkqWR2Tm_6arDp6Ch)

![](https://lh5.googleusercontent.com/hfz80-BJL_a4C4BYHsBqJSUL-MSWuwKJ47IntoqzCfQApX8D2vhnfxsEchzazFmfudAy1SjZD0PsOoFkK1KvwG06mVuKQ8HoQT0uGB0SbGtayiidskeWXEIyPagWGvcZj9SSoGym)

![](https://lh4.googleusercontent.com/WNsFBx5U3H_e1v8HOeiFAiX1Yk_t0GySkkhosSAagO5kobd09-NiSrIAMlp3zn3FWg_8r5EywUPFMonproZOoUGeRmGclAPDHRoeWTLTe-vu_PM3DPdIqMrTs-l5kt8fX_aFN42r)

![](https://lh4.googleusercontent.com/c9n_gdI5FE6GB_fwTCY7bY73XgAE7Rgvidox_UVNLf65RNs37IGqPY4t6-2HfldUXVkcR35ZWVVFelU_nijxJDORT2tDuftYDeSLa8-3HdXe8X-pkhmIlNAt-4RhqGSZUs3FfxYh)

![](https://lh3.googleusercontent.com/hJBb8FQcaoXnm2QFShmC9adqkZopHnBhWC32x8LiYFnIcDmIj3QyX_LVKD4VZagOzo2ITIrII-ATKz8yyE6stLYtSvfTkqyw75vBTdaTsCw-fhMAn9ZknB0lVnn4wHfknUd3CdB8)

![](https://lh6.googleusercontent.com/mKeQ62OKXa-xsiSpe4S7xhwdiWucKMTszSB_dkplLN66TjyhsbDpSFTRXSmsglyTEK6VZ24o0rmwn9MIVD8TJZG6uT1M-Ob-NQKG3kMPFSn-qg6-Qf3gB312WE4VSUvZN7vap3Sn)

cc: @jinalfoflia

**Comment by Sowmya2321** [comment]
Our team has reverted the impacted changesets. The reverted changesets can be found [here](https://osmcha.org/filters?aoi=8c5f82dc-3772-4e6a-aec0-72e0e8f7fe62). No next actions, closing this ticket.
