### ISSUE TITLE
Reviewing and mapping POIs in Bangkok, Thailand

### ISSUE THREAD

**Issue by GRABOSM** [GRABOSM/Grab-Data#115]
**Objective:** Our Thailand local teams have surveyed and are adding/reviewing the existing POIs in the Bangkok region of Thailand. 

![Chaophraya_River_(8767097465)](https://user-images.githubusercontent.com/38514914/156132557-646625fa-76d1-46b3-987e-5ae7ae832211.jpg)

_By Nik Cyclist from Bangkok, Thailand - Chaophraya River, CC BY 2.0, https://commons.wikimedia.org/w/index.php?curid=57764490_

**Regions we are reviewing/mapping:**
Starting with the following city [cities]:

- Bangkok, TH

**Workflow:** These are collected using the survey, a small team will be adding them on OSM.

**Validation:** We'll be following the validation guidelines mentioned in our wiki: https://wiki.openstreetmap.org/wiki/Grab#Quality_Process

**Changeset Comment:** `Adding POIs: https://github.com/GRABOSM/Grab-Data/issues/115`

**Source:** MAXAR -- we would refer to others if need be.

**Filter:** None

**Plugins:** None

**Edge cases:** None at the moment, we'll post it as a subsequent comment if need be.

**Team involved:**[ Piriyada Chuenjai](https://www.openstreetmap.org/user/Piriyada%20Chuenjai)

**OSM Forum Link:** https://forum.openstreetmap.org/viewtopic.php?pid=856837#p856837

Do reach out to us if you have any questions or suggestions on the same. Happy Mapping!

cc: @jinalfoflia

**Comment by Polovinkin** [comment]
Hi guys, I'm a OSM contributor (https://www.openstreetmap.org/user/dpolovinkin), just want to notice that it seems that basically all POI which were added by [Piriyada Chuenjai](https://www.openstreetmap.org/user/Piriyada%20Chuenjai) are done incorrectly, did anyone familiar with how OSM works review it at all back then? 
Mainly issue is a mix of languages in the main name of POI, so like here https://www.openstreetmap.org/node/9710581611 the name is "Wufoo Wholesale Market Khon Kaen - ศูนย์ค้าส่ง อู้ฟู่ ขอนแก่น" when it actually should have Thai language name and English name separated like:
name=ศูนย์ค้าส่ง อู้ฟู่ ขอนแก่น
name:en=Wufoo Wholesale Market Khon Kaen
or maybe in reverse with name:th - but names in different languages must be put in separate tags.

And why did you add POI with duplicate info like that https://www.openstreetmap.org/node/9710945038 of the airport?  You've made terminal POI but added airport info... which is already there in the airport area...

so, just for you to know.

**Comment by GRABOSM** [comment]
Hi @Polovinkin, thank you for posting your concern regarding the POI added by [Piriyada Chuenjai](https://www.openstreetmap.org/user/Piriyada%20Chuenjai), our Thailand mapping team is going to review the mapped POIs by the mentioned user and fix the issues you've mentioned.

Thank you again for taking the time to report it and fixing the duplicate terminal. Happy Mapping!
