### ISSUE TITLE
Kaula lumpur

### ISSUE THREAD

**Issue by GRABOSM** [GRABOSM/Grab-Data#16]

**Comment by MASangys** [comment]
https://forum.openstreetmap.org/viewtopic.php?pid=708775#p708775

**Comment by GRABOSM** [comment]
Thanks for feedback MASangys.  We will check and revert asap

Lavanya

**Comment by GRABOSM** [comment]
Hello

Further continuation to the above message,
We ran the below query  with both the key words "Abandonded" and "Disused" in entire KL to find out if there are other instances where key value is changed from Abandoned - 
[out:xml][timeout:25][bbox:{{bbox}}];
(
 node["abandoned:highway"];
 way["abandoned:highway"];
 relation["abandoned:highway"];
);
(._;>;);
out meta;

We found three instances - 1 segment is changed by our team and its corrected, rest are not touched and are currently with the value as "Abandoned".
Hence wanted to confirm that we checked for similar instances across KL and found nothing inappropriate

Thanks again for your time

**Comment by MASangys** [comment]
Feel free to see this in the forum
https://forum.openstreetmap.org/viewtopic.php?id=19683

**Comment by GRABOSM** [comment]
Hello,

Thanks for the inputs.  We will review them and use as appropriate

Thanks 
Grab Team

**Comment by GRABOSM** [comment]
Hello,

Thanks for the inputs.  We will review them and use as appropriate

Thanks 
Grab Team

**Comment by GRABOSM** [comment]
Hello,

A quick help is required.  We have created an online doc and here is the link
Please take time to review and suggest
https://hackmd.io/u_wf-x0IRdeBLmGz25lSPg

Thanks
Grab Team

**Comment by MASangys** [comment]
I already posted in the Malaysian OSMer facebook group. (Komuniti OpenStreetMap Malaysia) And can your company give a user namelist that under the Grab Team?

**Comment by anushalanka** [comment]
Hello,

Thanks for the post in FB.  We will keep a tab on the comments.

Here is the [list ](https://github.com/GRABOSM/Grab-Data/blob/master/Grab%20Data%20Team)of users working under Grab Team.

Thanks,
Grab Team.

**Comment by GRABOSM** [comment]
Hello,

Thanks for the post in FB page. We will keep a tab on the comments from local team.

Here is the [list ](https://github.com/GRABOSM/Grab-Data/blob/master/Grab%20Data%20Team)of users working for Grab Team.

Thanks,
Grab Team.

**Comment by MASangys** [comment]
Please use Digital Global Standard Imagery first as it is newer and better. For more info please see this. https://forum.openstreetmap.org/viewtopic.php?id=19683

I noticed that your team are using older imagery and did you know you can change the imagery layer during edit? (especially iD editor)

**Comment by MASangys** [comment]
And please dont change any relation and naming for railway station in Klang Valley, beautify the shape or add parking and bus stop are welcome. This is because there have a subway validator http://osmz.ru/subways/malaysia.html and those information are useful for LRT/MRT navigation in application like MAPS.ME

**Comment by MASangys** [comment]
So where your team gonna update. Puchong? Subang Jaya or till Penang and JB?

**Comment by GRABOSM** [comment]
Hello 

As per our project scope(also mentioned in our project page) we do not work on entire city of KL.  We we only focus on the areas served by Grab and street naming and/or editing relations is not part of our scope.
With reference to the areas mentioned above - 
(1) Penang - We worked around airport covering 5KM radius, adding missing roads and/or correcting existing network.
(2) Puchon, Subang Jaya - These ares we will work only on specific locations served by Grab
(3) JB - This area is not part of our scope.
Trust we were able to answer your query.
Please let us know if you need any further information

Thanks
Grab Team

**Comment by GRABOSM** [comment]
No next actions here, please follow up on mapping projects in this ticket: https://github.com/GRABOSM/Grab-Data/issues/46 thank you for your help and suggestions. Happy Mapping!
