### ISSUE TITLE
Road alignment/accuracy efforts

### ISSUE THREAD

**Issue by govvin** [GRABOSM/Grab-Data#18]
Hi there. 

I'm wondering if you are you utilizing the [imagery offset database](http://offsets.textual.ru/map) whenever you validate or update road alignments?

The IODb is an excellent tool to ensure consistency among mappers working in the same general area, and allow other mappers to replicate and validate the offset quickly.

**Comment by govvin** [comment]
That is the conventional approach to road alignment, which is easiest for beginners. However, I believe Grab is also serious about ensuring positional accuracy of road networks, knowing how important that is for their usecase.

There are numerous instances where the base imagery is not aligned correctly, resulting in existing objects that will follow the same mis-alignment. There are imagery with offsets that are over 10m, especially older imagery.

The ideal approach is to align whatever aerial imagery you're using with public SatNav tracks, or Strava, and record those offsets in IODb for consistency and ease of replicating.  While IODb is not yet useful for iD users, JOSM users, Vespucci editors can take advantage of it to ensure correct alignment.

**Comment by GRABOSM** [comment]
Thanks for the lead Gowin.  We also refer to Strava pings along with grab traces(this is not public and cant be downloaded) before deciding if a segment needs alignment correction.

Along with this approach miving forward we will refer to the database mentioned and start updating as appropriate.

A quick question.  Can we use this approach for all countries or is this something specific followed by Malaysian mappers community.

As always thanks for your time to share your learnings with us.

Grab Team

**Comment by GRABOSM** [comment]
Surely will get in touch.  You are a great support.  Thanks again..

We joined telegram.  😊

**Comment by GRABOSM** [comment]
Hello Erwin,
Closing this issue as we are clarified on the usage of offset database. 
Thanks
Grab Team
