### ISSUE TITLE
Bangkok Map Enhancement Efforts

### ISSUE THREAD

**Issue by GRABOSM** [GRABOSM/Grab-Data#21]
Hello Mappers,

We are team from Grab about to start work on OSM enhancing the map for Bangkok
We only concentrate on the areas served by Grab and not the entire city and we only focus on enhancing map for road network.

We have done a pre analysis on sample areas in Bangkok and found that there is more scope for adding missing roads, while existing data corrections are very minimal.
We identified that Bing Imagery is well aligned with existing data and strava gps, however, in some areas, when zoomed in, imagery is found cloudy.
Hence in such instances we will refer to digi standard imagery to identify missing roads, but will come back to Bing imagery for creation and/or alignment.
We also checked with IODB (Imagery Offset Database) to check for any existing offsets recorded and we did not find any.  We will keep a track and record relevant offsets while we continue working on the city

While we will refer to Thailand WIKI page for country specific policies to be followed, kindly suggest if there are any other sources to be referred. 

Here are some examples screen shots of missing road instances we found(these are only examples and do not comprise of the entire work we intended to do in the city)
Lat/long : 13.6200621, 100.9861301
                 13.6203705, 101.0308112
                 13.575821, 101.0322584
                13.5797174, 100.9920735
![image](https://user-images.githubusercontent.com/38514914/43758273-3a95a478-9a39-11e8-9b8b-58e743a2a46a.png)

Lat/long : 14.1060741, 100.5472513
                 14.1052308, 100.5928349
                 14.0586207, 100.5929865
                14.0592748, 100.5474533
![image](https://user-images.githubusercontent.com/38514914/43758346-737f432a-9a39-11e8-9cfc-62bbfc46f35f.png)

Thanks in advance
Grab Team

**Comment by Russ-McD** [comment]
Dear Grab team,
Please be aware a there is feedback on your work occuring in the OSM Thai User Forum at:
[https://forum.openstreetmap.org/viewtopic.php?id=64075](url)
as well as in some changeset comments.
Looking at the above pictures, Yes, there are roads missing in Thailand, especially in the rural areas. But, you will be aware that we have recently had a team from Facebook importing roads using Machine Learning (AI) techniques.  This has caused a disaster locally, as anything that resembled a road, was tagged as "residential".
I fear that you may follow the same footsteps, unless you fully understand our tagging conventions.  Basically, if you see a "road" you want to add, please ensure that **unless you can be 100% sure** it has a paved surface, then tag it as either **surface=unpaved**, or if in a rural area, most likely as a "**track**".
And resist the temptation to add small roads that are in fact, the driveway to properties, and often have access is restricted by a gate.
Regards,
Russ McDermid (Thai based OSM mapper).

**Comment by GRABOSM** [comment]
Closing this ticket, capturing the recent mapping efforts in Thailand in ticket #49.
