### ISSUE TITLE
Service Vs Residential Roads

### ISSUE THREAD

**Issue by GRABOSM** [GRABOSM/Grab-Data#22]
Hello Everyone,

We refer to wiki for the policies related to identifying if a road is  service or residential.
In this context, there are certain cases where we need further help on identifying the right road priority
Here listed are few real time instances we tried to replicate.
Kindly take time to suggest if the hints we are referring to while deciding road priority can be generalized across countries.  Would be of great help if we can get any other documentations that can be referred to for clarity.  
![image](https://user-images.githubusercontent.com/38514914/44199331-6567c800-a161-11e8-910a-10fecac037fb.png)

![image](https://user-images.githubusercontent.com/38514914/44199637-4453a700-a162-11e8-9d98-184e1bd096ad.png)

![image](https://user-images.githubusercontent.com/38514914/44200506-5e8e8480-a164-11e8-8e0c-3110a5c73e96.png)

![image](https://user-images.githubusercontent.com/38514914/44201276-78c96200-a166-11e8-845a-d1fd3e14e54b.png)

Thanks in advance
Grab Team

**Comment by govvin** [comment]
If it's a residential complex, the blue segments are `highway=residential`. The general rule for residential roads is that they provide access to housing areas and properties.

**Comment by GRABOSM** [comment]
Thanks Erwin.  

Few Questions Please - 
1) Does that mean that any road providing access to housing areas and properties are residential irrespective of connectivity?
2) What if we have such roads leading to commercial property?
3) "Service" is given only at instances of roads within cemeteries, parking lots, industrial areas etc.  else, in general roads are marked as highway = residential 

Thanks
Lavanya

**Comment by govvin** [comment]
My apologies for having to delete the earlier post, I was mobile, and I wanted to elaborate using your images.

> ![](https://user-images.githubusercontent.com/38514914/44199331-6567c800-a161-11e8-910a-10fecac037fb.png)
> If this complex is purely residential, `highway=residential` is acceptable. The purpose of residential road is to provide access to properties, regardless of connectivity to the rest of the network. 
> If the complex is mix-used, `highway=unclassified` may be used.

> ![](https://user-images.githubusercontent.com/38514914/44199637-4453a700-a162-11e8-9d98-184e1bd096ad.png)
> The blue segments here may use `highway=service` or `highway=residential`, which may depend on **local** convention. There's also `highway=living_street` for residential areas, but in some countries this has a specific legal meaning, while in other countries, the local mappers define the convention.

> ![](https://user-images.githubusercontent.com/38514914/44200506-5e8e8480-a164-11e8-8e0c-3110a5c73e96.png)
> Do you mean to say the polygon is a parking area? If so, the blue segments are `highway=service`


> ![](https://user-images.githubusercontent.com/38514914/44201276-78c96200-a166-11e8-845a-d1fd3e14e54b.png)
> Residential roads doesn't require pass-through connectivity to the road network. Red segment should be `highway=residential`. The blue segments are `highway=service`+ `service=driveway`

For your questions:

1. In geneal, yes. Although in some residential complexes such as residential high rises, they may just be `highway=service`.
2. Roads within commercial or retail complex may be tagged as `highway=unclassified`, or just `highway=service` for smaller areas.
3. Not necessarily. The most common road type is probably `highway=residential`, but these may be upgraded depending on local road traffic. 

Road tagging in OSM is functional.  Connector roads that lead hamlets from small villages may use `highway=unclassified`, bigger villages and small towns connect with `highway=tertiary`. Significance of these settlements are subjectives, and  that's just the global convention, however, local practice may vary. 

See the [highway key](https://wiki.openstreetmap.org/wiki/Key:highway) wiki page, in addition to local mapping conventions.

**Comment by GRABOSM** [comment]
Thanks for your time in helping us with detailed explanation.
Case 3 - I meant that the complex could be anything - residential or
commercial or parking lot or Industrial area.

One last question please -
For Case 4 - Why are giving highway = service for blue colored segments
instead of highway - residential?  Is it because they are individual houses
instead of high rise buildings?

Thanks
Lavanya

**Comment by govvin** [comment]
> For Case 4 - Why are we giving highway = service for blue colored segments instead of highway = residential? Is it because they are individual houses instead of high rise buildings?

Most highway tags imply shared use. `highway=service` are often limited to property owners or tenants. In your example, you wrote that the polygons are houses, so I made the assumption that these are detached houses, and those roads are driveways. Ergo, `highway=service` + `service=driveway` is a likely tag to use.

**Comment by govvin** [comment]
A "complex" cannot just be anything. Like I wrote earlier, if mixed-use, use `highway=unclassified` or higher. If purely residential, then `highway=residential` should be okay.

**Comment by GRABOSM** [comment]
Hello Govvin,

Thanks for your guidance.  Closing this thread now as it is sorted

Lavanya

**Comment by mishari** [comment]
This is the kind of thing that should be documented on the Wiki, please do so as well as any other similar info about what you're doing.
