### ISSUE TITLE
Map Enhancement Efforts in Specific Malaysian Cities

### ISSUE THREAD

**Issue by GRABOSM** [GRABOSM/Grab-Data#25]
Hello Mappers,

We are team from Grab about to start work on OSM enhancing the map for the below mentioned Malaysian cities - 
Johor Bahru, 
Penang, 
Kuching, 
Kota Kinabalu
As per our scope of work, we only concentrate on the areas served by Grab and not the entire city and we only focus on enhancing map for road network.
Basis our preliminary analysis for these cities, identified that ESRI is best imagery to be used.
While we follow the standard OSM guidelines for mapping, posting the request here for help from local community best practices or country specific mapping guidelines to be followed.

Thanks in advance
Grab Team

**Comment by MASangys** [comment]
As a OSM mapper I would like to suggest the Grab mapper to prioritize update those area which is lack of street/outdated map
Johor Bahru-Tebrau, Skudai (Taman Seri Austin)
Penang-Air Itam, Sungai Nibong, Bayan Lepas, Tanjung Bungah, Butterworth, Sungai Bakap.

**Comment by MASangys** [comment]
BTW I have a question, since Grab application used the Google Maps as their navigation background, how the OSM street data will bring benefits to the Grab company.

**Comment by MASangys** [comment]
And can your company give a user namelist agin that under this task?

**Comment by GRABOSM** [comment]
Here is the [link](https://github.com/GRABOSM/Grab-Data/blob/master/Grab%20Data%20Team) of Grab users

**Comment by MASangys** [comment]
OK, but I noticed that some Grab users tag rural road as unclassified, I found those around Balik Pulau and Kuala Muda (hopefully someone help to trace the road), only use residential road for planned residential area, for hamlet (kampung) the highway=unclassified is better and highway=track for non residential small road.

**Comment by GRABOSM** [comment]
Thanks MaSangys for the feedback and help
We will check and correct such instances

Thanks
Grab Team

**Comment by GRABOSM** [comment]
Hello MaSangys,

We are not aware of policies around assigning grades for segments, hence we
just map missing roads and assign appropriate priority, just to ensure we
do not downgrade the map quality

Thanks
Grab Team

**Comment by GRABOSM** [comment]
Closing this ticket, capturing the recent mapping efforts in Malaysia in this ticket #46.
