### ISSUE TITLE
Map Enhancement Efforts in Thailand City - Chiang Mai

### ISSUE THREAD

**Issue by GRABOSM** [GRABOSM/Grab-Data#27]
Hello Mappers,

We are team from Grab about to start work on OSM enhancing the map for Thailand City - Chiang Mai
As per our scope of work, we only concentrate on the areas served by Grab and not the entire city and we only focus on enhancing map for road network.
Basis our preliminary analysis for these cities, identified that ESRI and BING is best imagery to be used.
While we follow the standard OSM guidelines for mapping, posting the request here for help from local community best practices or country specific mapping guidelines to be followed.
We have created a new issue in our project page.  For any questions and/or feedback please drop in a message

Thanks in advance
Grab Team

**Comment by stephankn** [comment]
You can reach the Thailand community in the Thailand section of the forum: https://forum.openstreetmap.org/viewforum.php?id=46

**Comment by stephankn** [comment]
Please explain why you believe that esri and bing are the best imagery to be used. Based on what did you decide this?

**Comment by GRABOSM** [comment]
Hello,

We take sample areas across the city and analyze the following to decide
which imagery is the best and can be used as default.

1. See if there are any existing imagery offsets used by other mappers
2. See which imagery is used by other mappers while mapping existing data.
3. And check imagery with which the existing data best matches with no or
less offset.

Basis the above points we are intending to use bing and esri as default.
Please suggest otherwise
However rest images will also be referred to check for any additional
roads.

Thanks
Grab Team

**Comment by GRABOSM** [comment]
Closing this ticket, capturing the recent mapping efforts in Thailand in this ticket #49.
