### ISSUE TITLE
Fixing the dual carriage-ways mapped without a physical barrier

### ISSUE THREAD

**Issue by GRABOSM** [GRABOSM/Grab-Data#37]
### **Objective**

- There are several dual carriage-ways mapped where there is no physical barrier and this is in turn affecting routing seriously in Singapore as the routing engines are routing through illegal and un-allowed u turns because of the one-ways.
- The lack of connector segments between the two roads is also causing an issue in exiting from condos and the like in taking turns.
- These dual carriage-ways need to be sorted out to minimize the error and routing inconsistencies.
- However, due to major bus relations applied to the roads, editing and making this a single carriageway is complicated.
- This ticket is to highlight the issue caused due to wrongly mapped dual carriage-ways and the steps taken to ensure the correction of the data.

Issue: directions

![image](https://lh3.googleusercontent.com/oDIcssrJN-EQIfBOhkQ6u6MbjOzSxcx-HNJuuOBI6Lz-LbMB11cdxg-M-w91CdEBWgSrbNGJ9we2wyCf_6HD6WsuS7LBMYSJBadANFEGc86Wyacdhaseq1OVTc2Y66TqHfz614u2)

 *No discernible physical median*

![image](https://lh3.googleusercontent.com/2Fgc2bPcpQHVRAZJM2A-J7o0vsF2yGHu-QnMLIK8Nuxqkqk3NM3v10oL-b4dFTg6WwC5we1t2SkqZq3c47zEYiQPz3pg1B4hiQuJ5JuWBR1dL5XKCm6HfpBwUSPddqP_I2UenBpU)

 
*As seen in OpenStreet Cam*

![image](https://lh3.googleusercontent.com/_gd1OB2nPJqBqvHXy7VM5mSruqhUEsiMtCmvnwsVUjISYLjlzi7na6uahtUfEH8r3Q5mz4_KeJKfpcKkTov6r2CiNaY-sd2-ovI9m3NvFLKWu7_OfPTkp3qAacTOMAWFSpx5YzwC)

 
*OSRM routing through a service road inside of a residential area because of no u-turns between the connectors*

![image](https://lh5.googleusercontent.com/JXTn55VuzcewreAD9FvSLzZuMEbFxAW043JwSBH16LstU1qOKPATlsDbyNyatnbvhN-aTKWTX9CEKNaYLzkAUDKDI9pLFHO5bI9X4uTgspEL2F8rt3PQgzDWulQaz1l6Mpb7yTjx)

 *No of bus relations per road in this junction*

### **Solution: Workflow**
- The only way the routing will be resolved here is by removing that part of the street from the bus relations.
- Since it is a dual carriage-way, the bus relations added will be different, as the routes followed would be different.
- So while making this a single carriageway, the order followed for the members should be correctly aligning with the `from` and `to` of each side.
- This can only be done in phases so that we don't break the entire relation.

**Here's how you can do that:**

- Click on the way in question, verify the way id number and check the relations the way is a part of.
![image](https://lh3.googleusercontent.com/ytCR4L9sYhXpBTnnhBVL0kasgOnrmH4yjxEZ571fOvS-LjYYKVvZuD2Dknb_W-YJBsuWLDOrD9VELqYHUUJ6qtEl432zIWiwnXDGojeMhbMoyW7n23wikuI4bdVpA0Gr41vWF5_j)

- Select individual relations, click on edit to see the members list of the relation.
![image](https://lh3.googleusercontent.com/arFZ1jOLKN80wlI8-yUwHOsUkMIId9ukECtu9EzhbdmlLMoW6yPmmIjuQAgofokWtcFDP5wQs4bcqs4-0n07BO6CX1J5Y1g8FlMYM5Ww-BzXSD1XeLOqtRodkI-vwADYZJA4P6FZ)

- Carefully verify the way id number and delete that way id from the relation members list.
![image](https://lh4.googleusercontent.com/ZLnIvF0zCa_gDao502nOq3hn7R2XXbA3iuIbDNSYUN_IlvNCey75ewnlSW2mz-ekftk3DzNEmGtC1xLrOeZHNGTT7zZvRJe13xWf-qszkp6zDHOW9NQpBLBxAxJ172Y-owsZG7c5)

- Remove both the relations from each side of the dual carriageway but make sure to do it with just a single way id every time. Check the route numbers of the buses so you can simultaneously one single route for the members.
![image](https://lh4.googleusercontent.com/hsIuml-_bchFoE-ZOs0qTH0mRI-vFgs8lZwbn_lqCGZWnGgCCZWnTWIDRGGM5Jclry6uC0UyXfDXG3zLWFXj29D0GQUkUHTNqqMVg2ZoShrXY7AM5ijQvKrolFKdfX89R8E_wnic)

- Remove the members from all the relations, before making that a single carriageway. And then add that corresponding way id to both the relations
- This way, you are only deleting unwanted members of the relation while retaining the relation as a whole.
- While validating, please check and verify that there are no routes broken.

**Changeset Comment**: `Fixing the dual carriage-ways mapped without a physical barrier https://github.com/GRABOSM/Grab-Data/issues/37 #Grab`

**Source:** Digital Globe Standard, Bing Aerial Imagery, ESRI World Imagery, and Maxar for freshness, OpenStreetCam and Mapillary

**Filter:** None

**Plugins:** None

**Edge cases:** None at the moment, we'll post it as a subsequent comment if need be.

**Team involved:** @poornibadrinath 

Do reach out to us if you have any questions or suggestions on the same. Happy Mapping! 

cc: @jinalfoflia

**Comment by JaLooNz** [comment]
I disagree that the data is wrongly mapped, as the mapping is done in greater detail and follows[ "on-the-ground" rules first and foremost](https://wiki.openstreetmap.org/wiki/How_We_Map). Tagging conventions shall be secondary to having accurate data that follows what is on-the-ground, especially when people writing on the Wiki may not have considered cases such as mapping of Transport routes. As such, it is my position that we should not be downgrading/simplifying the data just for the sake of following some conventions that may be applied in other countries/cities that may not have the level of detail that we are seeing here.

In this case here, mapping of bus routes without utilising dual ways will lead to [duplication in bus route service especially on Transport maps](http://öpnvkarte.de/?zoom=12&lat=1.35584&lon=103.80787&layers=TBTTT#103.9378;1.3136;18). This is clearly not the desired outcome, and if your team insists on doing that will only mean that you are prioritising your own use case against the use case of others whom rely on the same data.

In the [OSRM](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=1.31421%2C103.93948%3B1.31166%2C103.94028#map=19/1.31450/103.93952)example sent via PM, the issue of the excessively long route appears to be due the [originating service route (which was added by the Grab mapping team) not extending to the other side of the road](https://www.openstreetmap.org/way/644925238), and is only connected to [one way](https://www.openstreetmap.org/node/6063807161).

**Comment by GRABOSM** [comment]
@JaLooNz thank you for the feedback, the detailed explanation of the data and the underlying issues that can be caused if the roads are made single carriageway. We agree with your points and are not going to edit any relations or make the roads single carriageway. Please do let us know if there is any other way to approach this issue. Thank you, no next actions here, closing this issue.
