### ISSUE TITLE
Curved way and other issues

### ISSUE THREAD

**Issue by mishari** [GRABOSM/Grab-Data#93]
Hi,

This way https://www.openstreetmap.org/way/754797269 is curved when the road is actually straight.

There's a barrier here when in actual fact none exists https://www.openstreetmap.org/node/7050972564

There are geometries like this that are quite awful, please make sure they represent the road and maintain symmetry if the ways are symmetrical.
https://www.openstreetmap.org/way/628208686#map=19/13.75437/100.52687
https://www.openstreetmap.org/way/628208706

There are these strange hockey stick shaped ways that seem to be all over the place, could these be cleaned up?
https://www.openstreetmap.org/way/628208656
https://www.openstreetmap.org/way/628208702
https://www.openstreetmap.org/way/628457227

**Comment by GRABOSM** [comment]
@mishari, thank you for bringing these edits to our notice. We are verifying the edits and we will make the required changes and update them soon.

**Comment by GRABOSM** [comment]
We have updated these changesets according to the suggestions given and confirmed some of the roads using the available imagery. For the ones that couldn't be confirmed, we have added a few notes. Linking the fixed changes here. Do let us know if there are any more changes by leaving a changeset comment. 


https://www.openstreetmap.org/changeset/107974236
https://www.openstreetmap.org/changeset/107974405
https://www.openstreetmap.org/changeset/107974878
https://www.openstreetmap.org/changeset/107985739#map=17/13.75243/100.52595
https://www.openstreetmap.org/changeset/107986746 
https://www.openstreetmap.org/changeset/107986850 

Closing this ticket as closed. Thank you for bringing the edits to our notice 

cc: @jinalfoflia @poornibadrinath @mishari
