### ISSUE TITLE
Grab editors modifying street names in the Philippines

### ISSUE THREAD

**Issue by govvin** [GRABOSM/Grab-Data#97]
I've noticed Grab editors modifying highway names in the Philippines, and replacing it with the short-form version of the street names (e.g. "P. Sanchez Street" to "Sanchez", "M. dela Fuente Street" to "Dela Fuente Street", etc. ). This is incorrect, and doesn't follow local conventions.

Street signs may likely use the short-form (because of space constraints) inconsistently, and should be used with caution, and editors should be careful when fully qualified names are already present.

I'm concerned that these edits are reducing the quality and resolution of data made by other contributors.

I also noticed that Grab editors were claiming that the street sign boards were found using KartaView imagery, but upon closer inspection, there are no public imagery available in said areas.

**Comment by GRABOSM** [comment]
@govvin, thank you for bringing this to our notice. We are checking and verifying on our end what edits have been made and rest assured, if they are wrong we will rectify them. 
However, some of the images in KartaView as mentioned as the source, the images are either in HQ or 360 panoramas. Do enable them for the traces. 

![karta](https://user-images.githubusercontent.com/38514914/127214726-958733e0-800d-4c63-abef-ee8d2e52a19c.gif)

Our written policy enforces not to change any edits without prior communication to the mapper or a verified source. We will reiterate that to the team and ensure these errors do not repeat. We are in the process of revisiting the edits made and verifying them again. 

We will soon update the progress on this ticket https://github.com/GRABOSM/Grab-Data/issues/80 and reach out to you if there are any questions.

**Comment by govvin** [comment]
Thank you for clarifying about HD and VR photos in KartaView.

I appreciate that you are going to re-visit the edits made related to this issue. Our community doesn't have the resources to go through all your team's edits.

To wit:
* where there are no name tags present, it's safe to use what's found in street signages
* if name values are already in OSM, and doesn't match what's found on signages, check whether more appropriate tags (short_name, alt_name) are more appropriate.
* if you have concerns, interact in our LoCo channels (most of us do not use GitHub): https://osm.org/wiki/PH

**Comment by GRABOSM** [comment]
@govvin absolutely! Thank you for sharing these sources. We will make sure to add these in our documents as well and consider this a country-specific policy for PH.

**Comment by GRABOSM** [comment]
Updates will be on #80. Closing this ticket as resolved
